enum ActionTypes {
  SET_CURRENT_CATALOG_ID = 'Catalog/SET_CURRENT_CATALOG_ID',
  FETCH_CATALOG_ITEM = 'Catalog/FETCH_CATALOG_ITEM',
  FETCH_CATALOG_LIST = 'Catalog/FETCH_CATALOG_LIST',
  FETCH_CATALOG_PROJECT_LIST = 'Catalog/FETCH_CATALOG_PROJECT_LIST',
  RESET_CATALOG_FORM = 'Catalog/RESET_CATALOG_FORM',
  CREATE_CATALOG = 'Catalog/CREATE_CATALOG',
  CREATE_CATALOG_REQUEST = 'Catalog/CREATE_CATALOG_REQUEST',
  UPDATE_CATALOG_REQUEST = 'Catalog/UPDATE_CATALOG_REQUEST',
  UPDATE_CATALOG = 'Catalog/UPDATE_CATALOG',
  FETCH_CATALOG = 'Catalog/FETCH_CATALOG',
  DELETE_CATALOG = 'Catalog/DELETE_CATALOG',
  DELETE_CATALOG_REQUEST = 'Catalog/DELETE_CATALOG_REQUEST',

  SET_CATALOG_PAGE = 'Catalog/SET_CATALOG_PAGE',

  RESET_CATALOG_ITEM = 'Catalog/RESET_CATALOG_ITEM',

  RESET_CATALOG_LIST = 'Catalog/RESET_CATALOG_LIST',
  RESET_MY_UPLOADED_FILES = 'Catalog/RESET_MY_UPLOADED_FILES',

  CREATE_FILES = 'Catalog/CREATE_FILES',

  CREATE_FILE = 'Catalog/CREATE_FILE',

  CREATE_FILE_REQUEST = 'Catalog/CREATE_FILE_REQUEST',
  UPDATE_FILE_REQUEST = 'Catalog/UPDATE_FILE_REQUEST',
  UPDATE_FILE = 'Catalog/UPDATE_FILE',

  UPDATE_CATALOG_FILE_REQUEST = 'Catalog/UPDATE_CATALOG_FILE',

  FETCH_MY_UPLOADED_FILES = 'Catalog/FETCH_MY_UPLOADED_FILES',

  CUT_VIDEO = 'Catalog/CUT_VIDEO',
  CUT_VIDEO_REQUEST = 'Catalog/CUT_VIDEO_REQEST',

  CATALOG_COPY = 'Catalog/CATALOG_COPY',
  CATALOG_PASTE = 'Catalog/CATALOG_PASTE'


}

export default ActionTypes
