enum ActionTypes {
  SET_CURRENT_CATALOG_ID = 'Catalog/SET_CURRENT_CATALOG_ID',
  SET_CATALOG_MEDIA_ITEM = 'Catalog/SET_CATALOG_MEDIA_ITEM',
  FETCH_CATALOG_ITEM_REQUEST = 'Catalog/FETCH_CATALOG_ITEM_REQUEST',
  FETCH_CATALOG_LIST = 'Catalog/FETCH_CATALOG_LIST',
  FETCH_CATALOG_FILES = 'Catalog/FETCH_CATALOG_FILES',
  FETCH_CATALOG_LIST_BY_IDS = 'Catalog/FETCH_CATALOG_LIST_BY_IDS',
  FETCH_CATALOG_PROJECT_LIST = 'Catalog/FETCH_CATALOG_PROJECT_LIST',
  RESET_CATALOG_FORM = 'Catalog/RESET_CATALOG_FORM',
  CREATE_CATALOG = 'Catalog/CREATE_CATALOG',
  CREATE_CATALOG_REQUEST = 'Catalog/CREATE_CATALOG_REQUEST',
  UPDATE_CATALOG_REQUEST = 'Catalog/UPDATE_CATALOG_REQUEST',
  MOVE_CATALOG_REQUEST = 'Catalog/MOVE_CATALOG_REQUEST',
  UPDATE_CATALOG = 'Catalog/UPDATE_CATALOG',
  FETCH_CATALOG = 'Catalog/FETCH_CATALOG',
  DELETE_CATALOG = 'Catalog/DELETE_CATALOG',
  DELETE_CATALOG_REQUEST = 'Catalog/DELETE_CATALOG_REQUEST',

  DELETE_MANY_CATALOG = 'Catalog/DELETE_MANY_CATALOG',
  DELETE_MANY_CATALOG_REQUEST = 'Catalog/DELETE_MANY_CATALOG_REQUEST',

  SET_CATALOG_PAGE = 'Catalog/SET_CATALOG_PAGE',

  RESET_CATALOG_ITEM = 'Catalog/RESET_CATALOG_ITEM',

  RESET_CATALOG_LIST = 'Catalog/RESET_CATALOG_LIST',
  RESET_MY_UPLOADED_FILES = 'Catalog/RESET_MY_UPLOADED_FILES',

  CREATE_FILES = 'Catalog/CREATE_FILES',

  CREATE_FILE = 'Catalog/CREATE_FILE',

  CREATE_FILE_REQUEST = 'Catalog/CREATE_FILE_REQUEST',
  UPDATE_FILE_REQUEST = 'Catalog/UPDATE_FILE_REQUEST',
  UPDATE_FILE = 'Catalog/UPDATE_FILE',

  CATALOG_ADD_TO_FAVORITE_REQUEST = 'Catalog/CATALOG_ADD_TO_FAVORITE_REQUEST',
  CATALOG_DELETE_FROM_FAVORITE_REQUEST = 'Catalog/CATALOG_ADD_TO_FAVORITE_REQUEST',
  CATALOG_ADD_TO_FAVORITE = 'Catalog/CATALOG_ADD_TO_FAVORITE',
  CATALOG_DELETE_FROM_FAVORITE= 'Catalog/CATALOG_DELETE_FROM_FAVORITE',


  UPDATE_CATALOG_FILE_REQUEST = 'Catalog/UPDATE_CATALOG_FILE',

  FETCH_MY_UPLOADED_FILES = 'Catalog/FETCH_MY_UPLOADED_FILES',

  CUT_VIDEO = 'Catalog/CUT_VIDEO',
  CUT_VIDEO_REQUEST = 'Catalog/CUT_VIDEO_REQEST',

  CATALOG_COPY = 'Catalog/CATALOG_COPY',
  CATALOG_PASTE = 'Catalog/CATALOG_PASTE',

  SET_FILES_FROM_DROPZONE = 'Catalog/SET_FILES_FROM_DROPZONE',
  RESET_FILES_FROM_DROPZONE = 'Catalog/RESET_FILES_FROM_DROPZONE',


}

export default ActionTypes
