enum ActionTypes {
  FETCH_CATALOG_PROJECTS_FAVORITE_LIST = 'Catalog/FETCH_CATALOG_PROJECT_FAVORITE_LIST',
  FETCH_CATALOG_FOLDERS_FAVORITE_LIST = 'Catalog/FETCH_CATALOG_FODLERS_FAVORITE_LIST',
  FETCH_CATALOG_FILES_FAVORITE_LIST = 'Catalog/FETCH_CATALOG_FILES_FAVORITE_LIST',
  RESET_FAVORITE = 'Catalog/RESET_FAVORITE'
}

export default ActionTypes
