enum ActionTypes {
  FETCH_JOB_LIST = 'Job/FETCH_JOB_LIST',
  FETCH_JOB_LIST_BY_IDS = 'Job/FETCH_JOB_LIST_BY_IDS',
  FETCH_ONE_JOB = 'Job/FETCH_ONE_JOB',
  SET_JOB_PAGE = 'Job/SET_JOB_PAGE',
  RESET_JOB_LIST = 'Job/REST_JOB_LIST',
  CANCEL_JOB = 'Job/CANCEL_JOB',
  DELETE_JOB = 'Job/DELETE_JOB',
  CANCEL_JOB_REQUEST = 'Job/CANCEL_JOB_REQUEST',
  DELETE_JOB_REQUEST = 'Job/DELETE_JOB_REQUEST',
}

export default ActionTypes
