version: '3'

networks:
  app:
    driver: bridge
  nginx-proxy:
    external: true
services:
    app:
        build:
          context: .
          dockerfile: docker/app/Dockerfile
          args:
            - ENV_FILE=.env.prod
        image: ${APP_IMAGE}
        container_name: sbercu-front-app
        restart: ${DK_RESTART}
        networks:
          - app
    nginx:
        build:
          context: .
          dockerfile: docker/nginx/Dockerfile
          args:
            - APP_IMAGE=${APP_IMAGE}
        image: ${NGINX_IMAGE}
        container_name: sbercu-front-nginx
        restart: ${DK_RESTART}
        networks:
          - app
          - nginx-proxy
        depends_on:
          - app
        environment:
          API_HOST: http://sber-cu-api-app
          VIRTUAL_HOST: dev.sbercu.glob-com.ru, www.dev.sbercu.glob-com.ru, dev.sbercu.firelabs.ru, www.dev.sbercu.firelabs.ru
          LETSENCRYPT_HOST: dev.sbercu.glob-com.ru, www.dev.sbercu.glob-com.ru, dev.sbercu.firelabs.ru, www.dev.sbercu.firelabs.ru
          LETSENCRYPT_EMAIL: sites.globcom@yandex.ru
          VIRTUAL_PORT: 80
