version: '3'

networks:
  app:
    driver: bridge
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        - ENV_FILE=.env.dev
    image: ${APP_IMAGE}
    container_name: sbercu-front-app
    restart: ${DK_RESTART}
    networks:
      - app
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        - APP_IMAGE=${APP_IMAGE}
    image: ${NGINX_IMAGE}
    container_name: sbercu-front-nginx-firelabs
    restart: ${DK_RESTART}
    networks:
      - app
    depends_on:
      - app
    environment:
      API_HOST: http://sber-cu-api-nginx
