enum ActionTypes {
  FETCH_TAG_CATEGORY_LIST = 'TagCategory/FETCH_TAG_CATEGORY_LIST',
  RESET_TAG_CATEGORY_LIST = 'TagCategory/RESET_TAG_CATEGORY_LIST',
  RESET_TAG_CATEGORY_FORM = 'TagCategory/RESET_TAG_CATEGORY_FORM',
  CREATE_TAG_CATEGORY = 'TagCategory/CREATE_TAG_CATEGORY',
  CREATE_TAG_CATEGORY_REQUEST = 'TagCategory/CREATE_TAG_CATEGORY_REQUEST',
  UPDATE_TAG_CATEGORY_REQUEST = 'TagCategory/UPDATE_TAG_CATEGORY_REQUEST',
  UPDATE_TAG_CATEGORY = 'TagCategory/UPDATE_TAG_CATEGORY',
  FETCH_TAG_CATEGORY = 'TagCategory/FETCH_TAG_CATEGORY',
  DELETE_TAG_CATEGORY = 'TagCategory/DELETE_TAG_CATEGORY',
  DELETE_TAG_CATEGORY_REQUEST = 'TagCategory/DELETE_TAG_CATEGORY_REQUEST',
  SET_CATEGORY_TYPE = 'TagCategory/SET_CATEGORY_TYPE',
 }

export default ActionTypes
