enum ActionTypes {
  FETCH_USER_LIST = 'User/FETCH_USER_LIST',
  RESET_USER_FORM = 'User/RESET_USER_FORM',
  CREATE_USER = 'User/CREATE_USER',
  CREATE_USER_REQUEST = 'User/CREATE_USER_REQUEST',
  UPDATE_USER_REQUEST = 'User/UPDATE_USER_REQUEST',
  UPDATE_USER = 'User/UPDATE_USER',
  FETCH_USER = 'User/FETCH_USER',
  DELETE_USER = 'User/DELETE_USER',
  DELETE_USER_REQUEST = 'User/DELETE_USER_REQUEST',
}

export default ActionTypes
