enum ActionTypes {
  PASSWORD_RESET_SUBMIT = 'PASSWORD_RESET/SUBMIT',
  PASSWORD_RESET_ERROR = 'PASSWORD_RESET/ERROR',
  PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET/SUCCESS',
  PASSWORD_RESET_RESET = 'PASSWORD_RESET/RESET',

}

export default ActionTypes
