enum ActionTypes {
  FETCH_TAG_LIST = 'Tag/FETCH_TAG_LIST',
  RESET_TAG_FORM = 'Tag/RESET_TAG_FORM',
  CREATE_TAG = 'Tag/CREATE_TAG',
  CREATE_TAG_REQUEST = 'Tag/CREATE_TAG_REQUEST',
  UPDATE_TAG_REQUEST = 'Tag/UPDATE_TAG_REQUEST',
  UPDATE_TAG = 'Tag/UPDATE_TAG',
  FETCH_TAG = 'Tag/FETCH_TAG',
  DELETE_TAG = 'Tag/DELETE_TAG',
  DELETE_TAG_REQUEST = 'Tag/DELETE_TAG_REQUEST',
 }

export default ActionTypes
