enum ActionTypes {
  SET_CURRENT_SPEAKER_ID = 'Speaker/SET_CURRENT_SPEAKER_ID',

  FETCH_SPEAKER_ITEM_REQUEST = 'Speaker/FETCH_SPEAKER_ITEM_REQUEST',
  FETCH_SPEAKER_LIST = 'Speaker/FETCH_SPEAKER_LIST',
  RESET_SPEAKER_FORM = 'Speaker/RESET_SPEAKER_FORM',

  SET_SPEAKER_ITEM = 'Speaker/SET_SPEAKER_ITEM',

  CREATE_SPEAKER = 'Speaker/CREATE_SPEAKER',
  CREATE_SPEAKER_REQUEST = 'Speaker/CREATE_SPEAKER_REQUEST',
  UPDATE_SPEAKER_REQUEST = 'Speaker/UPDATE_SPEAKER_REQUEST',
  UPDATE_SPEAKER = 'Speaker/UPDATE_SPEAKER',
  FETCH_SPEAKER = 'Speaker/FETCH_SPEAKER',
  DELETE_SPEAKER = 'Speaker/DELETE_SPEAKER',
  DELETE_SPEAKER_REQUEST = 'Speaker/DELETE_SPEAKER_REQUEST',

  SET_SPEAKER_PAGE = 'Speaker/SET_SPEAKER_PAGE',

  RESET_SPEAKER_ITEM = 'Speaker/RESET_SPEAKER_ITEM',

  RESET_SPEAKER_LIST = 'Speaker/RESET_SPEAKER_LIST',


  SPEAKER_ADD_TO_FAVORITE_REQUEST = 'Speaker/SPEAKER_ADD_TO_FAVORITE_REQUEST',
  SPEAKER_DELETE_FROM_FAVORITE_REQUEST = 'Speaker/SPEAKER_ADD_TO_FAVORITE_REQUEST',
  SPEAKER_ADD_TO_FAVORITE = 'Speaker/SPEAKER_ADD_TO_FAVORITE',
  SPEAKER_DELETE_FROM_FAVORITE= 'Speaker/SPEAKER_DELETE_FROM_FAVORITE',


}

export default ActionTypes
