enum ActionTypes {
  RESET_FEEDBACK_FORM = 'Catalog/RESET_FEEDBACK_FORM',
  CREATE_FEEDBACK = 'Catalog/CREATE_FEEDBACK',
  CREATE_FEEDBACK_REQUEST = 'Catalog/CREATE_FEEDBACK_REQUEST',

  UPDATE_FEEDBACK = 'Catalog/UPDATE_FEEDBACK',
  UPDATE_FEEDBACK_REQUEST = 'Catalog/UPDATE_FEEDBACK_REQUEST',

  DELETE_FEEDBACK = 'Catalog/DELETE_FEEDBACK',
  DELETE_FEEDBACK_REQUEST = 'Catalog/DELETE_FEEDBACK_REQUEST',

  FETCH_FEEDBACK_LIST = 'Catalog/FETCH_FEEDBACK_LIST',
  RESET_FEEDBACK_LIST = 'Catalog/RESET_FEEDBACK_LIST'
}

export default ActionTypes
