enum ActionTypes {
  FETCH_CATALOG_PROJECTS_DELETED_LIST = 'Catalog/FETCH_CATALOG_PROJECT_DELETED_LIST',
  FETCH_CATALOG_FOLDERS_DELETED_LIST = 'Catalog/FETCH_CATALOG_FODLERS_DELETED_LIST',
  FETCH_CATALOG_FILES_DELETED_LIST = 'Catalog/FETCH_CATALOG_FILES_DELETED_LIST',
  RESTORE_CATALOG_ITEM_REQUEST = 'Catalog/RESTORE_CATALOG_ITEM_REQUEST',
  DELETE_CATALOG_ITEM_REQUEST = 'Catalog/RESTORE_CATALOG_ITEM_REQUEST',
  CLEAN_BASKET_REQUEST = 'Catalog/CLEAN_BASKET',
  RESET_DELETED = 'Catalog/RESET_DELETED'
}

export default ActionTypes
