enum ActionTypes {
  CREATE_MEDIA_LINK_TEMP = 'MediaLink/CREATE_MEDIA_LINK_TEMP',
  CREATE_MEDIA_LINK_PUBLIC = 'MediaLink/CREATE_MEDIA_LINK_PUBLIC',
  CREATE_MEDIA_LINK_VIRTSCHOOL = 'MediaLink/CREATE_MEDIA_LINK_VIRTSCHOOL',
  RESET_MEDIA_LINK_FORM = 'MediaLink/RESET_MEDIA_LINK_FORM',
}

export default ActionTypes
