enum ActionTypes {
  RESET_AUTOCOMPLETE_SEARCH = 'Catalog/RESET_AUTOCOMPLETE_SEARCH',
  FETCH_CATALOG_PROJECTS_SEARCH_LIST = 'Catalog/FETCH_CATALOG_PROJECT_SEARCH_LIST',
  FETCH_CATALOG_FOLDERS_SEARCH_LIST = 'Catalog/FETCH_CATALOG_FODLERS_SEARCH_LIST',
  FETCH_CATALOG_FILES_SEARCH_LIST = 'Catalog/FETCH_CATALOG_FILES_SEARCH_LIST',
  FETCH_SPEAKERS_SEARCH_LIST = 'Catalog/FETCH_SPEAKERS_SEARCH_LIST',
  FETCH_AUTOCOMPLETE_CATALOG_PROJECTS_SEARCH_LIST = 'Catalog/FETCH_AUTOCOMPLETE_CATALOG_PROJECTS_SEARCH_LIST',
  FETCH_AUTOCOMPLETE_CATALOG_FOLDERS_SEARCH_LIST = 'Catalog/FETCH_AUTOCOMPLETE_CATALOG_FOLDERS_SEARCH_LIST',
  FETCH_AUTOCOMPLETE_CATALOG_FILES_SEARCH_LIST = 'Catalog/FETCH_AUTOCOMPLETE_CATALOG_FILES_SEARCH_LIST',
  FETCH_AUTOCOMPLETE_SPEAKERS_SEARCH_LIST = 'Catalog/FETCH_AUTOCOMPLETE_SPEAKERS_SEARCH_LIST',
  RESET_SEARCH = 'Catalog/RESET_SEARCH'
}

export default ActionTypes
