enum ActionTypes {
  FETCH_CATALOG_SEARCH_LIST = 'Catalog/FETCH_CATALOG_SEARCH_LIST',
  FETCH_AUTOCOMPLETE_CATALOG_SEARCH_LIST = 'Catalog/FETCH_AUTOCOMPLETE_CATALOG_SEARCH_LIST',

}

export default ActionTypes
