enum ActionTypes {
  CREATE_FOLDER = 'Modal/CREATE_FOLDER',
  EDIT_FILE = 'Modal/EDIT_FILE',
  TAG = 'Modal/MODAL_TAG',
  TAG_CATEGORY = 'Modal/TAG_CATEGORY',
  USER_MODAL = 'Modal/USER',
  MODAL_CLOSE = 'Modal/MODAL_CLOSE',
  CONFIRM_MODAL_OPEN = 'MODAL/CONFIRM_MODAL_OPEN',
  CHANGE_CONFIRM_DATA = 'MODAL/CHANGE_CONFIRM_DATA',
  UPLOAD_FILES = "MODAL/UPLOAD_FILES",
  VIDEO_EDITOR_CONFIRM = "MODAL/VIDEO_EDITOR_CONFIRM"
}

export default ActionTypes
