enum ActionTypes {
  CREATE_FOLDER = 'Modal/CREATE_FOLDER',
  EDIT_FILE = 'Modal/EDIT_FILE',
  TAG = 'Modal/MODAL_TAG',
  TAG_CATEGORY = 'Modal/TAG_CATEGORY',
  USER_MODAL = 'Modal/USER',
  MODAL_CLOSE = 'Modal/MODAL_CLOSE',
  CONFIRM_MODAL_OPEN = 'MODAL/CONFIRM_MODAL_OPEN',
  CHANGE_CONFIRM_DATA = 'MODAL/CHANGE_CONFIRM_DATA',
  UPLOAD_FILES = "MODAL/UPLOAD_FILES",
  VIDEO_EDITOR_CONFIRM = "MODAL/VIDEO_EDITOR_CONFIRM",
  VIDEO_CODE_MODAL = "MODAL/VIDEO_CODE_MODAL",
  FILE_POSTER_UPLOAD_MODAL = "MODAL/FILE_POSTER_UPLOAD_MODAL",
  MEDIA_LINK_TEMP_MODAL = "MODAL/MEDIA_LINK_TEMP_MODAL",
  MEDIA_LINK_PUBLIC_MODAL = "MODAL/MEDIA_LINK_PUBLIC_MODAL",
  MEDIA_LINK_VIRTSCHOOL_MODAL = "MODAL/MEDIA_LINK_VIRTSCHOOL_MODAL",
  PASTE_CATALOG_ITEM_DUPLICATE = "MODAL/PASTE_CATALOG_ITEM_DUPLICATE",

}

export default ActionTypes
