enum ActionTypes {
  CREATE_FOLDER = 'Modal/CREATE_FOLDER',
  TAG = 'Modal/MODAL_TAG',
  TAG_CATEGORY = 'Modal/TAG_CATEGORY',
  USER_MODAL = 'Modal/USER',
  MODAL_CLOSE = 'Modal/MODAL_CLOSE',
  CONFIRM_MODAL_OPEN = 'MODAL/CONFIRM_MODAL_OPEN',
  CHANGE_CONFIRM_DATA = 'MODAL/CHANGE_CONFIRM_DATA',
  UPLOAD_FILES = "MOADAL/UPLOAD_FILES"
}

export default ActionTypes
