enum ActionTypes {
  PASSWORD_RECOVERY_SUBMIT = 'PASSWORD_RECOVERY/SUBMIT',
  PASSWORD_RECOVERY_ERROR = 'PASSWORD_RECOVERY/ERROR',
  PASSWORD_RECOVERY_SUCCESS = 'PASSWORD_RECOVERY/SUCCESS',
  PASSWORD_RECOVERY_RESET = 'PASSWORD_RECOVERY/RESET',

}

export default ActionTypes
